### ISSUE TITLE
/food /h /bio weisen Message Fehler auf

### ISSUE THREAD

**Issue by robinstechprojects** [robinstechprojects/Better-Commands-Plugin#13]
Benutzt man die oben genannten Commands wird bei den GM commands die Message die in der Config eigestellt ist  gesendet und darunter sie strings anderer Befehle. Bei den anderen commands ganu so bloß das bei den anderen Commands wie im Screenshot zu sehen nur die "StringFehler"  gesendet werden
Beim Screenshot wurde so weit ich weiss /food genutzt

![2015-07-13_13 17 41](https://cloud.githubusercontent.com/assets/12137156/8648600/334349b4-2962-11e5-96eb-51526067a4f4.png)

**Comment by FroznMine** [comment]
Mach ich^^
