### ISSUE TITLE
/h /food und /bio gehen nicht ! 

### ISSUE THREAD

**Issue by ibornlp** [robinstechprojects/Better-Commands-Plugin#7]
Es mag an meinem Server liegen aber wenn ich die oben genannten Commands benutze wird vom Server : "Internal Server error [...] " zurück gegeben.

Wäre nett wenn du da nochmal drauf gucken könntest denn ich bin dumm und muss Unterrichtet werden ;-)

**Comment by FroznMine** [comment]
Bitte mal den kompletten Stack-Trace. Es gibt nichts hilfreicheres als zu wissen was zurückkam.

**Comment by ibornlp** [comment]
internal Server Error Please tell the Admin about this oder sowas

nichts wo mann was drauß schliessen könnte :-/

**Comment by ibornlp** [comment]
Kann aber auch an der KOmbination mit den anderen Plugins liegen !

**Comment by FroznMine** [comment]
Komplett heißt komplett.
Alles was er ausspuckt.
Nur mit dem Namen des Fehlers kann ich wenig anfangen. Ich weiß nicht wo was nicht geht.
